server:
  port: 8080

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: test_stream
          content-type: text/plain
          binder: local_rabbit
        output:
          destination: test_stream
          content-type: text/plain
          binder: local_rabbit

      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                virtual-host: /
                username: guest
                password: guest

logging:
  level:
    ROOT: INFO
    springstudy.cloudstream.source: DEBUG
