DROP TABLE singers IF EXISTS;

CREATE TABLE singers
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);


DROP TABLE albums IF EXISTS;

CREATE TABLE albums
(
    id         bigint generated by default as identity,
    title      varchar(255) not null,
    singer_id  bigint,
    created_at timestamp,
    updated_at timestamp,
    primary key (id)
);
