<?php
/**
 * PetType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Example\PetApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * pet service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Example\PetApi\Model;
use \Example\PetApi\ObjectSerializer;

/**
 * PetType Class Doc Comment
 *
 * @category Class
 * @package  Example\PetApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PetType
{
    /**
     * Possible values of this enum
     */
    const CAT = 'CAT';
    const MICE = 'MICE';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CAT,
            self::MICE,
        ];
    }
}


