server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/workspace/spring-study/spring-cloud/config-server/central-properties
  profiles:
    active: native