spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/spring_data_example?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: false
    properties:
      hibernate:
        batch_fetch_style: dynamic
        default_batch_fetch_size: 80
        show_sql: true
        format_sql: true
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
      # hibernate envers properties
      # @see https://docs.jboss.org/envers/docs/#configuration
      org.hibernate.envers.audit_table_suffix: _revisions
      org.hibernate.envers.revision_field_name: revision
      org.hibernate.envers.revision_type_field_name: revision_type