spring:
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:spring-data-example;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:file:./build/spring-data-example;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  hikari:
    auto-commit: false

  jpa:
    database: H2
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      # hibernate envers properties
      # @see https://docs.jboss.org/envers/docs/#configuration
      org.hibernate.envers.audit_table_suffix: _audit_log
