spring:
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    datasource:
        url: jdbc:mysql://localhost:3306/pessimistic_lock?serverTimezone=Asia/Seoul
        username: homestead
        password: secret
        initialization-mode: always

