package dev.appkr.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;
import dev.appkr.dynamodb.DynamoJpaConfiguration.LocalDateTimeConverter;
import java.time.LocalDateTime;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
@EqualsAndHashCode(of = {"id"})
@DynamoDBTable(tableName = "Comment")
public class Comment {

  @DynamoDBHashKey(attributeName = "id")
  @DynamoDBAutoGeneratedKey
  String id;

  @DynamoDBAttribute
  @DynamoDBIndexHashKey(globalSecondaryIndexName = "byMentionId")
  Integer mentionId;

  @DynamoDBAttribute
  String name;

  @DynamoDBAttribute
  String content;

  @DynamoDBAttribute
  @DynamoDBTyped(DynamoDBAttributeType.BOOL)
  boolean deleted;

  @DynamoDBAttribute
  @DynamoDBIndexRangeKey(globalSecondaryIndexName = "byMentionId")
  @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
  LocalDateTime createdAt;

  @DynamoDBAttribute
  @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
  LocalDateTime deletedAt;
}
