<?php
/**
 * PetApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Example\PetApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * pet service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Example\PetApi;

use \Example\PetApi\Configuration;
use \Example\PetApi\ApiException;
use \Example\PetApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PetApiTest Class Doc Comment
 *
 * @category Class
 * @package  Example\PetApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PetApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createPet
     *
     * createPet.
     *
     */
    public function testCreatePet()
    {
    }

    /**
     * Test case for getPet
     *
     * getPet.
     *
     */
    public function testGetPet()
    {
    }

    /**
     * Test case for listPets
     *
     * listPets.
     *
     */
    public function testListPets()
    {
    }
}
