spring:
  application:
    name: grpcserver

grpc:
  server:
    port: 8090

management:
  endpoints:
    web:
      exposure:
        include: ['health', 'info', 'metrics']
  endpoint:
    metrics.enabled: true
    info.enabled: true
    health.show-details: always
  info.git.mode: simple
