spring:
  application:
    name: grpcserver

server:
  port: 8081

grpc:
  server:
    port: 8090

management:
  endpoints:
    web:
      exposure:
        include: ['health', 'info', 'metrics']
  endpoint:
    metrics.enabled: true
    info.enabled: true
    health.show-details: always
  info.git.mode: simple

security:
  oauth2:
    client:
      access-token-uri: http://localhost:9999/oauth/token
      user-authorization-uri: http://localhost:9999/oauth/token
      client-id: internal
      client-secret: internal
      scope: web-app
      grant-type: client_credentials
      authorized-grant-type: password, client_credentials, refresh_token
    resource:
      jwk.key-set-uri: http://localhost:9999/.well-known/jwks.json
