spring:
  application:
    name: EurekaServer
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761
server:
  port: 8761
