spring:
  application.name: edge

  graphql:
    # Whether the endpoint that prints the schema is enabled.
    # Schema is available under spring.graphql.path + "/schema".
    schema.printer.enabled: true
    # Whether the default GraphiQL UI is enabled.
    # GET /graphiql
    graphiql.enabled: true

management:
  endpoints:
    web.exposure.include: '*'
