spring:
  application.name: edge

  graphql:
    # Whether the endpoint that prints the schema is enabled.
    # Schema is available under spring.graphql.path + "/schema".
    schema.printer.enabled: true
    # Whether the default GraphiQL UI is enabled.
    # GET /graphiql
    graphiql.enabled: true

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: backend-service
          uri: http://localhost:8081
          predicates:
            - Path=/backend/**
          filters:
            - RewritePath=/backend/?(?<segment>.*), /$\{segment}

  endpoints:
    web.exposure.include: '*'

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9999/.well-known/jwks.json
      client:
        provider:
          uaa:
            token-uri: http://localhost:9999/oauth/token
            jwk-set-uri: http://localhost:9999/.well-known/jwks.json
        registration:
          uaa:
            client-id: internal
            client-secret: internal
            scope: web-app
            authorization-grant-type: password, client_credentials, refresh_token
