server:
    port: 8080
    error:
        path: /error
spring:
    thymeleaf:
        cache: false
        enabled: true
        prefix: classpath:/templates/
        suffix: .html
    application:
        name: Bootstrap Spring Boot
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
        username: sa
        password: