spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liquibasedemo?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: homestead
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog-master.xml
    contexts: local
