logging:
    level:
        ROOT: INFO
        com.example.petservice: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql: trace

spring:
    profiles:
        active: dev
        include:
            - swagger
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:./build/h2db/petsvc;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MULTI_THREADED=FALSE
        username: sa
        password:

    jpa:
        database: H2
        open-in-view: false
        show-sql: true
        properties:
            hibernate.show_sql: true
            hibernate.format_sql: true
