spring:
  application:
    name: grpcclient

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9999/.well-known/jwks.json
      client:
        provider:
          uaa:
            token-uri: http://localhost:9999/oauth/token
            jwk-set-uri: http://localhost:9999/.well-known/jwks.json
        registration:
          uaa:
            client-id: internal
            client-secret: internal
            scope: web-app
            authorization-grant-type: password, client_credentials, refresh_token

grpc:
  client:
    hello-service:
      address: 'static://127.0.0.1:8090'
      negotiationType: plaintext

management:
  endpoints:
    web:
      exposure:
        include: ['health', 'info', 'metrics']
  endpoint:
    metrics.enabled: true
    info.enabled: true
    health.show-details: always
  info.git.mode: simple
