spring:
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: true
        hibernate:
            ddl-auto: create
    datasource:
        url: jdbc:mysql://localhost:3306/datacommons?serverTimezone=Asia/Seoul
        username: homestead
        password: secret
