logging:
    level:
        ROOT: INFO
        springstudy.querydsl: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql: trace

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:./build/h2db/querydsl;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MULTI_THREADED=FALSE
        name:
        username: sa
        password: secret
        hikari:
            auto-commit: false
    jpa:
        hibernate:
            ddl-auto: create
